sap.ui.jsview("zhr06_kapatool.chart", {                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
       /**                                                                                                                                                                                                                                                     
       * Specifies the Controller belonging to this View. In the case that it is                                                                                                                                                                               
       * not implemented, or that "null" is returned, this View does not have a                                                                                                                                                                                
       * Controller.                                                                                                                                                                                                                                           
       *&nbsp;                                                                                                                                                                                                                                                 
        * @memberOf zhr06_kapatool.chart                                                                                                                                                                                                                       
       */                                                                                                                                                                                                                                                      
       getControllerName : function() {                                                                                                                                                                                                                        
             return "zhr06_kapatool.chart";                                                                                                                                                                                                                    
       },                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
       /**                                                                                                                                                                                                                                                     
       * Is initially called once after the Controller has been instantiated. It                                                                                                                                                                               
       * is the place where the UI is constructed. Since the Controller is given                                                                                                                                                                               
       * to this method, its event handlers can be attached right away.                                                                                                                                                                                        
       *&nbsp;                                                                                                                                                                                                                                                 
        * @memberOf zhr06_kapatool.chart                                                                                                                                                                                                                       
       */                                                                                                                                                                                                                                                      
       createContent : function(oController) {                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
             sap.ui.core.BusyIndicator.show(0);                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
             var oBundle = jQuery.sap.resources({                                                                                                                                                                                                              
                    url : "i18n/translation.properties"                                                                                                                                                                                                        
             });                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
             var oDataTable = sap.ui.getCore().byId("dataTable");                                                                                                                                                                                              
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                 
             if (oDataTable == null) {                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
                 var gBegda = '20150401';                                                                                                                                                                                                                      
                 var gEndda = '20150601';                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
                 var gCumulative = 'X';                                                                                                                                                                                                                        
                 var gEditable = 'X';                                                                                                                                                                                                                          
                 var gOrgeh = '99999999';                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
                 var oParametersInitial = {};                                                                                                                                                                                                                  
                 oParametersInitial.Begda = gBegda;                                                                                                                                                                                                            
                 oParametersInitial.Endda = gEndda;                                                                                                                                                                                                            
                 oParametersInitial.Cumulative = gCumulative;                                                                                                                                                                                                  
                 oParametersInitial.Orgeh = gOrgeh;                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
                 oTreeTable = oController.getTreeTable(gBegda, gEndda, gEditable);                                                                                                                                                                             
                 $.when(oController.fillTreeTable(oTreeTable, oParametersInitial)).then(function(oTreeTable) {                                                                                                                                                 
                                                                                                                                                                                                                                                               
                        sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                      
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                               
                        // hier noch sämtlichen Code vom else durchlaufen                                                                                                                                                                                      
                        // zur Not doppelt Coding                                                                                                                                                                                                              
                        var oCombination = oController.convertToFlat(oDataTable);                                                                                                                                                                              
                        console.log("oCombinationif");                                                                                                                                                                                                         
                        console.log(oCombination);                                                                                                                                                                                                             
                        return oCombination;                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
                 });                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
	          }                                                                                                                                                                                                                                                   
	          else {                                                                                                                                                                                                                                              
	        	&nbsp;&nbsp;                                                                                                                                                                                                                                         
	        	  // TODO hier prüfen ob combination richtig returned wird                                                                                                                                                                                           
	        	&nbsp;&nbsp;                                                                                                                                                                                                                                         
//	        	  var oModel = oDataTable.getModel().getProperty("/root");                                                                                                                                                                                         
//	        	  console.log("oModelChart");                                                                                                                                                                                                                      
//        		  console.log(oModel);                                                                                                                                                                                                                             
	        	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                             
	              // hier noch sämtlichen Code vom else durchlaufen                                                                                                                                                                                               
	              // zur Not doppelt Coding                                                                                                                                                                                                                       
//        		  oDataTable.setModel(oModel);                                                                                                                                                                                                                     
	              var oCombination = oController.convertToFlat(oDataTable);                                                                                                                                                                                       
	              console.log("oCombinationelseif");                                                                                                                                                                                                              
	              console.log(oCombination);                                                                                                                                                                                                                      
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                          
	              sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                               
	              return oCombination;                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	        	                                                                                                                                                                                                                                                     
	          }                                                                                                                                                                                                                                                   
//	             var oTreeJSON = oDataTable.getModel().getProperty("/root");                                                                                                                                                                                    
//	             var oTreeAll = new Array();                                                                                                                                                                                                                    
//	             var graphTitle = oTreeJSON[0].Title;                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
//	             // convert to flat                                                                                                                                                                                                                             
//	             for (var i = 0; i < oTreeJSON.length; i++) { // 1st                                                                                                                                                                                            
//	                    oTreeAll.push(oTreeJSON[i]);                                                                                                                                                                                                            
//	                    if (oTreeJSON[i].children.length > 0) {                                                                                                                                                                                                 
//	                          for (var d = 0; d < oTreeJSON[i].children.length; d++) { // 2nd                                                                                                                                                                   
//	                                 oTreeAll.push(oTreeJSON[i].children[d]);                                                                                                                                                                                   
//	                                 if (oTreeJSON[i].children[d].children.length > 0) {                                                                                                                                                                        
//	                                       for (var e = 0; e < oTreeJSON[i].children[d].children.length; e++) {                                                                                                                                                 
//	                                              oTreeAll.push(oTreeJSON[i].children[d].children[e]);                                                                                                                                                          
//	                                              if (oTreeJSON[i].children[d].children[e].children.length > 0) {                                                                                                                                               
//	                                                    for (var g = 0; g < oTreeJSON[i].children[d].children[e].children.length; g++) {                                                                                                                        
//	                                                           oTreeAll.push(oTreeJSON[i].children[d].children[e].children[g]);                                                                                                                                 
//	                                                    }                                                                                                                                                                                                       
//	                                              }                                                                                                                                                                                                             
//	                                       }                                                                                                                                                                                                                    
//	                                 }                                                                                                                                                                                                                          
//	                          }                                                                                                                                                                                                                                 
//	                    }                                                                                                                                                                                                                                       
//	             }                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                        
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                
//	         var data = oController.transpose(oTreeAll);                                                                                                                                                                                                        
//             // console.log(data);                                                                                                                                                                                                                           
//                                                                                                                                                                                                                                                             
//             var dataset = new sap.viz.ui5.data.FlattenedDataset({                                                                                                                                                                                           
//                    dimensions : [                                                                                                                                                                                                                           
//                          {                                                                                                                                                                                                                                  
//                                 axis : 1,                                                                                                                                                                                                                   
//                                 name : oBundle.getText("TreeTableColumnReport"),                                                                                                                                                                            
//                                 value : "{Mon01}"                                                                                                                                                                                                           
//                          }                                                                                                                                                                                                                                  
//                    ],                                                                                                                                                                                                                                       
//                    measures : [                                                                                                                                                                                                                             
//                          {                                                                                                                                                                                                                                  
//                                 name : oBundle.getText("EmpTableIstKapa"),                                                                                                                                                                                  
//                                 value : '{Mon03}'                                                                                                                                                                                                           
//                          }, {                                                                                                                                                                                                                               
//                                 name : oBundle.getText("EmpTableMaxGenKapa"),                                                                                                                                                                               
//                                 value : '{Mon02}'                                                                                                                                                                                                           
//                          },                                                                                                                                                                                                                                 
//                    ],                                                                                                                                                                                                                                       
//                    data : {                                                                                                                                                                                                                                 
//                          path : "/d"                                                                                                                                                                                                                        
//                    }                                                                                                                                                                                                                                        
//             });                                                                                                                                                                                                                                             
//                                                                                                                                                                                                                                                             
//             var oChartModel = new sap.ui.model.json.JSONModel();                                                                                                                                                                                            
//             oChartModel.setData(data);                                                                                                                                                                                                                      
//                                                                                                                                                                                                                                                             
//             var combination = new sap.viz.ui5.Combination("combiChart", {                                                                                                                                                                                   
//                    width : "90%",                                                                                                                                                                                                                           
//                    title : {                                                                                                                                                                                                                                
//                          visible : true,                                                                                                                                                                                                                    
//                          text : graphTitle                                                                                                                                                                                                                  
//                    },                                                                                                                                                                                                                                       
//                    toolTip : {                                                                                                                                                                                                                              
//                          preRender : function(tooltipDomNode) {                                                                                                                                                                                             
//                                 // Called before render tooltip.                                                                                                                                                                                            
//                                                                                                                                                                                                                                                             
//                                 // console.log(tooltipDomNode[0][0].textContent);                                                                                                                                                                           
//                                 //                                                                                                                                                                                                                          
//                                 // tooltipDomNode.append('div').text('Append more                                                                                                                                                                           
//                                 // information in default tooltip.').style({                                                                                                                                                                                
//                                 // 'font-weight' : 'bold'                                                                                                                                                                                                   
//                                 // });                                                                                                                                                                                                                      
//                                 //                                                                                                                                                                                                                          
//                                 // console.log("pre");                                                                                                                                                                                                      
//                                 // console.log(tooltipDomNode);                                                                                                                                                                                             
//                                                                                                                                                                                                                                                             
//                          },                                                                                                                                                                                                                                 
//                          postRender : function(tooltipDomNode) {                                                                                                                                                                                            
//                                 // Called after tooltip is renderred.                                                                                                                                                                                       
//                                 // console.log("post");                                                                                                                                                                                                     
//                                 // console.log(tooltipDomNode);                                                                                                                                                                                             
//                          },                                                                                                                                                                                                                                 
//                    // selectData : function(e) {                                                                                                                                                                                                            
//                    // var aSelectData = e.getParameter("data");                                                                                                                                                                                             
//                    // var oDataset = this.getDataset();                                                                                                                                                                                                     
//                    //                                                                                                                                                                                                                                       
//                    // for (var i = 0; i < aSelectData.length; i++) {                                                                                                                                                                                        
//                    // var oDataPoint = aSelectData[i];                                                                                                                                                                                                      
//                    // for (var j = 0; j < oDataPoint.data.length; j++) {                                                                                                                                                                                    
//                    // var oPath = oDataPoint.data[j].ctx.path;                                                                                                                                                                                              
//                    // var oContext = oDataset.findContext(oPath);                                                                                                                                                                                           
//                    // console.log(oContext);                                                                                                                                                                                                                
//                    // }                                                                                                                                                                                                                                     
//                    // }                                                                                                                                                                                                                                     
//                    //                                                                                                                                                                                                                                       
//                    // var popOver = new sap.m.Popover({                                                                                                                                                                                                     
//                    // placement : sap.m.PlacementType.Right,                                                                                                                                                                                                
//                    // content : "",                                                                                                                                                                                                                         
//                    // });                                                                                                                                                                                                                                   
//                    //                                                                                                                                                                                                                                       
//                    // if (popOver.isOpen()) {                                                                                                                                                                                                               
//                    // popOver.close();                                                                                                                                                                                                                      
//                    // }                                                                                                                                                                                                                                     
//                    // else {                                                                                                                                                                                                                                
//                    //                                      popOver.openBy(this, selected);                                                                                                                                                                  
//                    //                               }                                                                                                                                                                                                       
//                    //                        },                                                                                                                                                                                                             
//                                                                                                                                                                                                                                                             
//                    },                                                                                                                                                                                                                                       
//                    dataset : dataset,                                                                                                                                                                                                                       
//             });                                                                                                                                                                                                                                             
//                                                                                                                                                                                                                                                             
//             combination.setModel(oChartModel);                                                                                                                                                                                                              
//             sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                               
//             return combination;                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
       }                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               