sap.ui.jsview("zhr06_kapatool.planning", {                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
	/**                                                                                                                                                                                                                                                           
	 * Specifies the Controller belonging to this View. In the case that it is                                                                                                                                                                                    
	 * not implemented, or that "null" is returned, this View does not have a                                                                                                                                                                                     
	 * Controller.                                                                                                                                                                                                                                                
	 *&nbsp;                                                                                                                                                                                                                                                      
	 * @memberOf zhr06_kapatool.planning                                                                                                                                                                                                                          
	 */                                                                                                                                                                                                                                                           
	getControllerName : function() {                                                                                                                                                                                                                              
		return "zhr06_kapatool.planning";                                                                                                                                                                                                                            
	},                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/**                                                                                                                                                                                                                                                           
	 * Is initially called once after the Controller has been instantiated. It                                                                                                                                                                                    
	 * is the place where the UI is constructed. Since the Controller is given                                                                                                                                                                                    
	 * to this method, its event handlers can be attached right away.                                                                                                                                                                                             
	 *&nbsp;                                                                                                                                                                                                                                                      
	 * @memberOf zhr06_kapatool.planning                                                                                                                                                                                                                          
	 */                                                                                                                                                                                                                                                           
	createContent : function(oController) {                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
		sap.ui.core.BusyIndicator.show(0);                                                                                                                                                                                                                           
		jQuery.sap.require("sap.ui.core.IconPool");                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
		var oMatrixLayout = new sap.ui.commons.layout.MatrixLayout({                                                                                                                                                                                                 
			columns : 2,                                                                                                                                                                                                                                                
			layoutFixed : false,                                                                                                                                                                                                                                        
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		var oCell1 = new sap.ui.commons.layout.MatrixLayoutCell({                                                                                                                                                                                                    
			colSpan : 1,                                                                                                                                                                                                                                                
			hAlign : sap.ui.commons.layout.HAlign.Center,                                                                                                                                                                                                               
			vAlign : sap.ui.commons.layout.VAlign.Middle,                                                                                                                                                                                                               
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		var oCell2 = new sap.ui.commons.layout.MatrixLayoutCell({                                                                                                                                                                                                    
			colSpan : 1,                                                                                                                                                                                                                                                
			hAlign : sap.ui.commons.layout.HAlign.Center,                                                                                                                                                                                                               
			vAlign : sap.ui.commons.layout.VAlign.Middle,                                                                                                                                                                                                               
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		var sUri1 = sap.ui.core.IconPool.getIconURI("add");                                                                                                                                                                                                          
		var sUri2 = sap.ui.core.IconPool.getIconURI("cause");                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
		var btnAdd = new sap.m.Button({                                                                                                                                                                                                                              
			text : oBundle.getText("PlanningAdd"),                                                                                                                                                                                                                      
			icon : sUri1,                                                                                                                                                                                                                                               
			press : oController.addButtonHandler,                                                                                                                                                                                                                       
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		var btnAbgrenz = new sap.m.Button({                                                                                                                                                                                                                          
			text : "Austritt pflegen",//oBundle.getText("PlanningAbgrenz"),                                                                                                                                                                                             
			icon : sUri2,                                                                                                                                                                                                                                               
			press : oController.abgrenzButtonHandler,                                                                                                                                                                                                                   
		})                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		// Alternative                                                                                                                                                                                                                                               
		// btnAddButton.attachPress(oController.addButtonHandler)                                                                                                                                                                                                    
		// btnAbgrenzButton.attachPress(oController.abgrenzButtonHandler)                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
		oCell1.addContent(btnAdd)                                                                                                                                                                                                                                    
		oCell2.addContent(btnAbgrenz)                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
		oMatrixLayout.createRow(oCell1, oCell2);                                                                                                                                                                                                                     
		sap.ui.core.BusyIndicator.show(0);                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		var table = sap.ui.getCore().byId("selEmpTable");                                                                                                                                                                                                            
		if (table != null) {                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
			oEmployeePlanningTable = table;                                                                                                                                                                                                                             
			sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		}                                                                                                                                                                                                                                                            
		else {                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
			oEmployeePlanningTable = oController.getEmployeePlanningTable();                                                                                                                                                                                            
			$.when(oController.fillEmployeePlanningTable(oEmployeePlanningTable)).then(function() {                                                                                                                                                                     
                                                                                                                                                                                                                                                               
				console.log("done");                                                                                                                                                                                                                                       
				sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
			});                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
		}                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
		oEmployeePlanningTable.addExtension(oMatrixLayout);                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		return oEmployeePlanningTable;                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
	}                                                                                                                                                                                                                                                             
});                                                                                                                                                                                                                                                            