sap.ui.jsview("zhr06_kapatool.employee", {                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
	/**                                                                                                                                                                                                                                                           
	 * Specifies the Controller belonging to this View. In the case that it is                                                                                                                                                                                    
	 * not implemented, or that "null" is returned, this View does not have a                                                                                                                                                                                     
	 * Controller.                                                                                                                                                                                                                                                
	 *&nbsp;                                                                                                                                                                                                                                                      
	 * @memberOf zhr06_kapatool.employee                                                                                                                                                                                                                          
	 */                                                                                                                                                                                                                                                           
	getControllerName : function() {                                                                                                                                                                                                                              
		return "zhr06_kapatool.employee";                                                                                                                                                                                                                            
	},                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/**                                                                                                                                                                                                                                                           
	 * Is initially called once after the Controller has been instantiated. It                                                                                                                                                                                    
	 * is the place where the UI is constructed. Since the Controller is given                                                                                                                                                                                    
	 * to this method, its event handlers can be attached right away.                                                                                                                                                                                             
	 *&nbsp;                                                                                                                                                                                                                                                      
	 * @memberOf zhr06_kapatool.employee                                                                                                                                                                                                                          
	 */                                                                                                                                                                                                                                                           
	createContent : function(oController) {                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
		jQuery.sap.require("sap.ui.core.util.Export");                                                                                                                                                                                                               
		jQuery.sap.require("sap.ui.core.util.ExportTypeCSV");                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
		// TODO oShell is undefined                                                                                                                                                                                                                                  
		var oShell = sap.ui.getCore().byId("MainShell");                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
		var oMatrixLayout = new sap.ui.commons.layout.MatrixLayout({                                                                                                                                                                                                 
			columns : 4,                                                                                                                                                                                                                                                
			layoutFixed : false,                                                                                                                                                                                                                                        
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		var oCellBackButton = new sap.ui.commons.layout.MatrixLayoutCell({                                                                                                                                                                                           
			colSpan : 1,                                                                                                                                                                                                                                                
			hAlign : sap.ui.commons.layout.HAlign.Center,                                                                                                                                                                                                               
			vAlign : sap.ui.commons.layout.VAlign.Middle,                                                                                                                                                                                                               
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		var oCellExportButton = new sap.ui.commons.layout.MatrixLayoutCell({                                                                                                                                                                                         
			colSpan : 1,                                                                                                                                                                                                                                                
			hAlign : sap.ui.commons.layout.HAlign.Center,                                                                                                                                                                                                               
			vAlign : sap.ui.commons.layout.VAlign.Middle,                                                                                                                                                                                                               
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		var sUriBack = sap.ui.core.IconPool.getIconURI("nav-back");                                                                                                                                                                                                  
		var sUriExport = sap.ui.core.IconPool.getIconURI("download");                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
		var btnBack = new sap.m.Button({                                                                                                                                                                                                                             
			text : oBundle.getText("Back"),                                                                                                                                                                                                                             
			icon : sUriBack,                                                                                                                                                                                                                                            
			press : oController.backButtonHandler                                                                                                                                                                                                                       
		})                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		var btnExport = new sap.m.Button({                                                                                                                                                                                                                           
			text : oBundle.getText("Export"),                                                                                                                                                                                                                           
			icon : sUriExport,                                                                                                                                                                                                                                          
			press : oController.exportButtonHandler                                                                                                                                                                                                                     
		})                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		oCellBackButton.addContent(btnBack);                                                                                                                                                                                                                         
		oCellExportButton.addContent(btnExport);                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
		var oCellWhereAmI = new sap.ui.commons.layout.MatrixLayoutCell({                                                                                                                                                                                             
			colSpan : 2,                                                                                                                                                                                                                                                
			hAlign : sap.ui.commons.layout.HAlign.Center,                                                                                                                                                                                                               
			vAlign : sap.ui.commons.layout.VAlign.Middle,                                                                                                                                                                                                               
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		var sWhereAmI = window.gClickedRowLongtext + " " + oBundle.getText("GeneralFor") + " " + window.gClickedMonthYear;                                                                                                                                           
                                                                                                                                                                                                                                                               
		oCellWhereAmI.addContent(new sap.ui.commons.TextView({                                                                                                                                                                                                       
			text : sWhereAmI,                                                                                                                                                                                                                                           
			design : sap.ui.commons.TextViewDesign.H4,                                                                                                                                                                                                                  
		}));                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
		oMatrixLayout.createRow(oCellBackButton, oCellExportButton, oCellWhereAmI);                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
		sap.ui.core.BusyIndicator.show(0);                                                                                                                                                                                                                           
		var oShell = sap.ui.getCore().byId("MainShell");                                                                                                                                                                                                             
		oEmployeeTable = oController.getEmployeeTable();                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
		$.when(oController.fillEmployeeTable(oEmployeeTable)).then(function(oEmployeeTable) {                                                                                                                                                                        
                                                                                                                                                                                                                                                               
			oShell.setContent(oEmployeeTable);                                                                                                                                                                                                                          
			sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                                           
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		oEmployeeTable.addExtension(oMatrixLayout);                                                                                                                                                                                                                  
	}                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            