sap.ui.jsview("zhr06_kapatool.main", {                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
	/**                                                                                                                                                                                                                                                           
	 * Specifies the Controller belonging to this View. In the case that it is                                                                                                                                                                                    
	 * not implemented, or that "null" is returned, this View does not have a                                                                                                                                                                                     
	 * Controller.                                                                                                                                                                                                                                                
	 *&nbsp;                                                                                                                                                                                                                                                      
	 * @memberOf zhr06_kapatool.main                                                                                                                                                                                                                              
	 */                                                                                                                                                                                                                                                           
	getControllerName : function() {                                                                                                                                                                                                                              
		return "zhr06_kapatool.main";                                                                                                                                                                                                                                
	},                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/**                                                                                                                                                                                                                                                           
	 * Is initially called once after the Controller has been instantiated. It                                                                                                                                                                                    
	 * is the place where the UI is constructed. Since the Controller is given                                                                                                                                                                                    
	 * to this method, its event handlers can be attached right away.                                                                                                                                                                                             
	 *&nbsp;                                                                                                                                                                                                                                                      
	 * @memberOf zhr06_kapatool.main                                                                                                                                                                                                                              
	 */                                                                                                                                                                                                                                                           
	createContent : function(oController) {                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
		// Globals                                                                                                                                                                                                                                                   
		var gRole = '';                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
		// Get Configuration                                                                                                                                                                                                                                         
		$.when(oController.getMasterdata()).then(function(data) {                                                                                                                                                                                                    
                                                                                                                                                                                                                                                               
			// Fill Globals                                                                                                                                                                                                                                             
			gRole = data.d.UserRole; // PR, PC, AD, FK, SH                                                                                                                                                                                                              
			window.gRole = gRole;                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
			// // User Language                                                                                                                                                                                                                                         
			// var gLanguage = data.d.UserLanguage;                                                                                                                                                                                                                     
			// var gLanguage = "de-DE"                                                                                                                                                                                                                                  
			// console.log(gLanguage)                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
			// sLocale =                                                                                                                                                                                                                                                
			// sap.ui.getCore().getConfiguration().setLanguage(gLanguage);                                                                                                                                                                                              
			// var getLanguage = new                                                                                                                                                                                                                                    
			// sap.ui.getCore().getConfiguration().setLanguage(gLanguage);                                                                                                                                                                                              
			//                                                                                                                                                                                                                                                          
			// var sCurrentLocale =                                                                                                                                                                                                                                     
			// sap.ui.getCore().getConfiguration().getLanguage();                                                                                                                                                                                                       
			// console.log("Current: " + sCurrentLocale);                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
			// var sCurrentLocal = sLocale;                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
			// Fill Locals                                                                                                                                                                                                                                              
			console.log(data);                                                                                                                                                                                                                                          
			var oUser = data.d.UserName + " (" + data.d.UserOrgunit + ") ";                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
			var oView = sap.ui.getCore().byId("planning");                                                                                                                                                                                                              
			if (oView == undefined)                                                                                                                                                                                                                                     
				oView = new sap.ui.view({                                                                                                                                                                                                                                  
					id : "planning",                                                                                                                                                                                                                                          
					viewName : "zhr06_kapatool.planning",                                                                                                                                                                                                                     
					type : sap.ui.core.mvc.ViewType.JS                                                                                                                                                                                                                        
				});                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
			// Shell - Buildup                                                                                                                                                                                                                                          
			var oMasterShell = new sap.ui.ux3.Shell("MainShell", {                                                                                                                                                                                                      
				appTitle : "Personalplanung",//oBundle.getText("ShellHeadlineMinTitle"),                                                                                                                                                                                   
				// appIcon : "images/trumpf_log.png",                                                                                                                                                                                                                      
				showLogoutButton : true,                                                                                                                                                                                                                                   
				showSearchTool : false,                                                                                                                                                                                                                                    
				showInspectorTool : false,                                                                                                                                                                                                                                 
				showFeederTool : false,                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                               
				headerItems : [                                                                                                                                                                                                                                            
					new sap.ui.commons.TextView({                                                                                                                                                                                                                             
						text : oUser,                                                                                                                                                                                                                                            
					})                                                                                                                                                                                                                                                        
				],                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
				content : [                                                                                                                                                                                                                                                
					oView                                                                                                                                                                                                                                                     
				],                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
				worksetItems : [                                                                                                                                                                                                                                           
					new sap.ui.ux3.NavigationItem("PL", {                                                                                                                                                                                                                     
						key : "planning",                                                                                                                                                                                                                                        
						text : oBundle.getText("ShellPaneBarTitleEmps")                                                                                                                                                                                                          
					}), new sap.ui.ux3.NavigationItem("TR", {                                                                                                                                                                                                                 
						key : "tree",                                                                                                                                                                                                                                            
						text : "Abteilungssicht", //oBundle.getText("ShellHeadlineTitle")                                                                                                                                                                                        
					}), new sap.ui.ux3.NavigationItem("CH", {                                                                                                                                                                                                                 
						key : "chart",                                                                                                                                                                                                                                           
						text : "Auswertung",//oBundle.getText("ShellHeadlineChart")                                                                                                                                                                                              
					})                                                                                                                                                                                                                                                        
				],                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
				worksetItemSelected : oController.worksetItemSelected,                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
				paneBarItems : [                                                                                                                                                                                                                                           
					new sap.ui.core.Item("PI_Date", {                                                                                                                                                                                                                         
						key : "pi_strukt",                                                                                                                                                                                                                                       
						text : oBundle.getText("ShellPaneBarTitle"),                                                                                                                                                                                                             
					})                                                                                                                                                                                                                                                        
				],                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
				paneBarItemSelected : function(oEvent) {                                                                                                                                                                                                                   
					var sKey = oEvent.getParameter("key");                                                                                                                                                                                                                    
					var oShell = oEvent.oSource;                                                                                                                                                                                                                              
					switch (sKey) {                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
						case "pi_strukt" :                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
							var viewTree = sap.ui.getCore().byId("tree");                                                                                                                                                                                                           
							var viewPlanning = sap.ui.getCore().byId("planning");                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
							if (viewTree != null || viewPlanning != null) {                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
								if (viewTree.sId == "tree" || viewPlanning.sId == "planning") {                                                                                                                                                                                        
									var lDropdownLayout = sap.ui.getCore().byId("viewSelection");                                                                                                                                                                                         
									if (lDropdownLayout == null) {                                                                                                                                                                                                                        
										// console.log("Panel-Creation");                                                                                                                                                                                                                    
										var oDropdownLayout = oController.getSelectionDropdowns();                                                                                                                                                                                           
										oShell.setPaneContent(oDropdownLayout, false);                                                                                                                                                                                                       
										break;                                                                                                                                                                                                                                               
									}                                                                                                                                                                                                                                                     
									else {                                                                                                                                                                                                                                                
										// console.log("Panel Exists");                                                                                                                                                                                                                      
										oShell.setPaneContent(lDropdownLayout, false);                                                                                                                                                                                                       
										break;                                                                                                                                                                                                                                               
									}                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
								}                                                                                                                                                                                                                                                      
								else {                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
									sap.ui.getCore().byId("MainShell").closePane();                                                                                                                                                                                                       
									jQuery.sap.require("sap.ui.commons.MessageBox");                                                                                                                                                                                                      
									sap.ui.commons.MessageBox.show("Bitte nur in Datentabelle verwenden.", sap.ui.commons.MessageBox.Icon.ERROR);                                                                                                                                         
									sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
									break;                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
								}                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
							}                                                                                                                                                                                                                                                       
							else {                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
								// Auskommentiert, da Fehlermeldung bei                                                                                                                                                                                                                
								// initialem Laden der Seite                                                                                                                                                                                                                           
								// sap.ui.getCore().byId("MainShell").closePane();                                                                                                                                                                                                     
								//                                                                                                                                                                                                                                                     
								// jQuery.sap.require("sap.ui.commons.MessageBox");                                                                                                                                                                                                    
								// sap.ui.commons.MessageBox.show("Bitte nur in                                                                                                                                                                                                        
								// Datentabelle verwenden.",                                                                                                                                                                                                                           
								// sap.ui.commons.MessageBox.Icon.ERROR);                                                                                                                                                                                                              
								// sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                                   
								//                                                                                                                                                                                                                                                     
								// break;                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
							}                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
						default :                                                                                                                                                                                                                                                
							break;                                                                                                                                                                                                                                                  
					}                                                                                                                                                                                                                                                         
				},                                                                                                                                                                                                                                                         
			});                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
			// placing at content                                                                                                                                                                                                                                       
			oMasterShell.placeAt("content");                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
	}                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            