sap.ui.jsview("zhr06_kapatool.tree", {                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
	/**                                                                                                                                                                                                                                                           
	 * Specifies the Controller belonging to this View. In the case that it is                                                                                                                                                                                    
	 * not implemented, or that "null" is returned, this View does not have a                                                                                                                                                                                     
	 * Controller.                                                                                                                                                                                                                                                
	 *&nbsp;                                                                                                                                                                                                                                                      
	 * @memberOf zhr06_kapatool.tree                                                                                                                                                                                                                              
	 */                                                                                                                                                                                                                                                           
	getControllerName : function() {                                                                                                                                                                                                                              
		return "zhr06_kapatool.tree";                                                                                                                                                                                                                                
	},                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/**                                                                                                                                                                                                                                                           
	 * Is initially called once after the Controller has been instantiated. It                                                                                                                                                                                    
	 * is the place where the UI is constructed. Since the Controller is given                                                                                                                                                                                    
	 * to this method, its event handlers can be attached right away.                                                                                                                                                                                             
	 *&nbsp;                                                                                                                                                                                                                                                      
	 * @memberOf zhr06_kapatool.tree                                                                                                                                                                                                                              
	 */                                                                                                                                                                                                                                                           
	createContent : function(oController) {                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
		sap.ui.core.BusyIndicator.show(0);                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		var treeTab = sap.ui.getCore().byId("dataTable");                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
		if (treeTab == null) {                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
			// Initialer Aufruf (4 Monate + eigene Orgeh & Cumulative)                                                                                                                                                                                                  
			var currentDate = new Date();                                                                                                                                                                                                                               
			var x = 3; // + 3 months                                                                                                                                                                                                                                    
			var laterEndDate = new Date();                                                                                                                                                                                                                              
			laterEndDate = new Date(laterEndDate.getFullYear(), (laterEndDate.getMonth() + x), 0);                                                                                                                                                                      
                                                                                                                                                                                                                                                               
			var gBegda = '';                                                                                                                                                                                                                                            
			var gEndda = '';                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
			var gBegdaYear = currentDate.getFullYear().toString();                                                                                                                                                                                                      
			var gBegdaMonth = currentDate.getMonth() + 1;                                                                                                                                                                                                               
			if (gBegdaMonth < 10) {                                                                                                                                                                                                                                     
				gBegdaMonth = '0' + gBegdaMonth.toString();                                                                                                                                                                                                                
			}                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
			gBegdaMonth = gBegdaMonth.toString();                                                                                                                                                                                                                       
			gBegda = gBegdaYear + gBegdaMonth + '01';                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
			var gEnddaYear = laterEndDate.getFullYear().toString();                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
			var gEnddaMonth = laterEndDate.getMonth() + 1;                                                                                                                                                                                                              
			if (gEnddaMonth < 10) {                                                                                                                                                                                                                                     
				gEnddaMonth = '0' + gEnddaMonth.toString();                                                                                                                                                                                                                
			}                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
			var gEnddaDay = laterEndDate.getDate();                                                                                                                                                                                                                     
			if (gEnddaDay < 10) {                                                                                                                                                                                                                                       
				gEnddaDay = '0' + gEnddaDay.toString();                                                                                                                                                                                                                    
			}                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
			gEnddaDay = gEnddaDay.toString();                                                                                                                                                                                                                           
			gEnddaMonth = gEnddaMonth.toString();                                                                                                                                                                                                                       
			gEndda = gEnddaYear + gEnddaMonth + gEnddaDay;                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
			var gCumulative = 'X';                                                                                                                                                                                                                                      
			var gEditable = 'X'; // used for getTreeTable                                                                                                                                                                                                               
			var gOrgeh = '99999999';                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                               
			var oParametersInitial = {};                                                                                                                                                                                                                                
			oParametersInitial.Begda = gBegda;                                                                                                                                                                                                                          
			oParametersInitial.Endda = gEndda;                                                                                                                                                                                                                          
			oParametersInitial.Cumulative = gCumulative;                                                                                                                                                                                                                
			oParametersInitial.Orgeh = gOrgeh;                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
			// Initialer Buildup                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
			oTreeTable = oController.getTreeTable(gBegda, gEndda, gEditable);                                                                                                                                                                                           
			$.when(oController.fillTreeTable(oTreeTable, oParametersInitial)).then(function(oTreeTable) {                                                                                                                                                               
                                                                                                                                                                                                                                                               
				sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                                          
				console.log("oTreeTable1");                                                                                                                                                                                                                                
				console.log(oTreeTable);                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
				return oTreeTable;                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
			});                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
		}                                                                                                                                                                                                                                                            
		else {                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
			oTreeTable = treeTab;                                                                                                                                                                                                                                       
			sap.ui.core.BusyIndicator.hide();                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
			return oTreeTable;                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		}                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	}                                                                                                                                                                                                                                                             
});                                                                                                                                                                                                                                                            